# Generated by Django 4.2 on 2024-11-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=144)),
                ('type', models.CharField(max_length=144)),
                ('price', models.FloatField()),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('image', models.ImageField(default='images/bee0d08e62abe1a0e670bca98719b83486b68ac55146a4f29f4254463aa1a42f.jpg', upload_to='images')),
                ('condition', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField()),
                ('status', models.CharField(max_length=144)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
