# Generated by Django 4.2 on 2024-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
