# Generated by Django 4.2 on 2024-11-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_agent_customuser_phone_number_and_more'),
        ('index', '0004_query_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='users.agent'),
        ),
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
