# Generated by Django 4.2 on 2024-11-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_property_agent_alter_query_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('new', 'Новая'), ('good', 'Хорошая'), ('needs_renovation', 'Нуждается в реновации')], max_length=144),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('commercial', 'Коммерчиская')], max_length=144),
        ),
    ]
